#' @title Plotting Correlations between selected variable and other variables in selected dataset
#' @description Creates visualizations for the correlations between variables
#' This function works with objects created using the `ryx` function.
#' @param x An object of class `ryx`, generated by the `ryx` function.
#' It contains the correlation, p-values, and level of significance between the selected variable and all the other variables
#' in the selected dataset.
#' @returns A plot object specific to the method. The function returns a visualization of the correlations between
#' the selected variable and all the other variables in the selected dataset.
#' @examples
#' # Example usage:
#' library(MASS)
#' object <- ryx(Boston, y="medv")
#' plot(object)
#' data(mtcars)
#' object2 <- ryx(mtcars, y="mpg")
#' plot(object2)
#' @export
plot.ryx <- function(x) {
  # Extract data frame from ryx object
  df <- x$df

  # Add direction column for plotting
  df$direction <- ifelse(df$r > 0, "positive", "negative")

  # Convert variables to a factor to maintain order in the plot
  df$variable <- factor(df$variable, levels = df$variable[order(abs(df$r), decreasing = TRUE)])

  # Load ggplot2 library
  library(ggplot2)

  # Create the plot
  ggplot(df, aes(x = abs(r), y = variable, color = direction)) +
    geom_point(size = 4) +
    geom_segment(aes(x = 0, xend = abs(r), y = variable, yend = variable)) +
    scale_color_manual(values = c("positive" = "blue", "negative" = "red")) +
    labs(
      title = paste("Correlations with", x$y),
      x = "Correlation (absolute value)",
      y = "Variables",
      color = "Direction"
    ) +
    theme_minimal() +
    theme(
      plot.title = element_text(size = 12),
      axis.title = element_text(size = 10),
      axis.text = element_text(size = 10)
    )
}

