#'@title Printing correlations between selected variable and other variables in selected dataset
#'@description Prints correlations between selected variable and other variables in selected dataset
#'@param x An object of class `ryx`, generated by the `ryx` function.
#' It contains the correlation, p-values, and level of significance between the selected variable and all the other variables
#' in the selected dataset.
#'@returns The function returns a formatted print of the correlations between
#' the selected variable and all the other variables in the selected dataset.
#' @examples
#' # Example usage:
#' library(MASS)
#' object <- ryx(Boston, y="medv")
#' print(object)
#' data(mtcars)
#' object2 <- ryx(mtcars, y="mpg")
#' print(object2)
#' @export
print.ryx <- function(x) {
  # Print the correlations, but exclude other parts of the object
  cat("Correlations of", x$y, "with variables:", paste(x$x, collapse = ", "), "\n")

  # Print the data frame (correlation results)
  print(x$df)
}
