#'@title Printing correlations between selected variable and other variables in selected dataset
#'@description Prints correlations between selected variable and other variables in selected dataset
#'@export
#'@param x An object of class `ryx`, generated by the `ryx` function.
#' It contains the correlation, p-values, and level of significance between the selected variable and specified
#' variables in the selected dataset. If none are specified, the selected variable will be
#' compared to all other numeric variables in the dataset, excluding itself.
#'@returns The function returns a formatted print of the correlations between
#' the selected variable and all the other variables in the selected dataset.
#' @examples
#' # Example usage:
#' library(MASS)
#' object <- ryx(Boston, y="medv")
#' print(object)
#' # Example that compares selected variable with specified variables from a given dataset
#' data(mtcars)
#' object2 <- ryx(mtcars, y = "mpg", x = c("qsec","gear","carb"))
#' print(object2)
print.ryx <- function(x) {
  # Print the correlations, but exclude other parts of the object
  cat("Correlations of", x$y, "with variables:", paste(x$x, collapse = ", "), "\n")

  # Print the data frame (correlation results)
  print(x$df)
}
