#' @title Prints a summary of the correlations between the selected variable and other variables in the dataset
#' @param x An object of class `ryx`, generated by the `ryx` function.
#' It contains the correlation, p-values, and significance levels between the selected variable and the other variables
#' in the selected dataset.
#' @return The function returns a printed summary including:
#'   - The variables being compared,
#'   - The median absolute correlation between the selected variable and the other variables,
#'   - The range of the correlations,
#'   - The number of variables that are significant at the p < 0.05 level.
#' @examples
#' # Example usage:
#' library(MASS)
#' object <- ryx(Boston, y="medv")
#' summary(object)
#' data(mtcars)
#' object2 <- ryx(mtcars, y="mpg")
#' summary(object2)
#' @export
summary.ryx <- function(x) {
  # Extract components from the ryx object
  y <- x$y
  variables <- x$x
  df <- x$df

  # Calculate the median absolute correlation
  median_abs_corr <- median(abs(df$r))

  # Calculate the range of absolute correlations
  abs_corr_range <- range(abs(df$r))

  # Count the number of significant correlations at p < 0.05
  significant_vars <- sum(df$p < 0.05)

  # Create the summary output
  cat("Correlating", y, "with", paste(variables, collapse = " "), "\n")
  cat("The median absolute correlation was", round(median_abs_corr, 3),
      "with a range from", round(abs_corr_range[1], 3), "to", round(abs_corr_range[2], 3), "\n")
  cat(significant_vars, "out of", length(variables),
      "variables were significant at the p < 0.05 level.\n")
}


